name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: true
      
    - name: Install dependencies
      run: npm install -g mermaid.cli

    - name: Build site
      run: |
        # Assuming you need to build the site, replace with your build commands
        # For example, if using Jekyll, you might run:
        # bundle exec jekyll build -d build
        echo "Building the site..."

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Replace `./build` with the output directory
